#!/bin/bash

### BEGIN INIT INFO
# Provides: scriptname
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start daemon at boot time
# Description: Enable service provided by daemon.
### END INIT INFO

echo 1 > /sys/kernel/mm/ksm/run
echo 10 > /proc/sys/vm/swappiness
echo 50 > /proc/sys/vm/vfs_cache_pressure

echo 1000000 > /proc/sys/fs/file-max
echo 3240000 > /proc/sys/net/ipv4/tcp_max_syn_backlog
echo 3240000 > /proc/sys/net/core/somaxconn

echo 0 > /proc/sys/net/ipv4/tcp_timestamps
echo 0 > /proc/sys/net/ipv4/tcp_window_scaling
echo 128 > /proc/sys/net/ipv4/ip_default_ttl

echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
echo 1 > /proc/sys/net/ipv4/conf/all/proxy_arp
echo 1 > /proc/sys/net/ipv4/conf/all/rp_filter

echo 2048 > /proc/sys/net/ipv4/tcp_max_syn_backlog
echo 16384 > /proc/sys/net/ipv4/udp_rmem_min
echo 16384 > /proc/sys/net/ipv4/udp_wmem_min

echo 40960 > /proc/sys/net/core/optmem_max
echo 16777216 > /proc/sys/net/core/rmem_default
echo 16777216 > /proc/sys/net/core/rmem_max
echo 5000 > /proc/sys/net/core/somaxconn
echo 16777216 > /proc/sys/net/core/wmem_default
echo 16777216 > /proc/sys/net/core/wmem_max
echo bbr > /proc/sys/net/ipv4/tcp_congestion_control
echo 10 > /proc/sys/net/ipv4/tcp_fin_timeout
echo 15 > /proc/sys/net/ipv4/tcp_keepalive_intvl
echo 5 > /proc/sys/net/ipv4/tcp_keepalive_probes
echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time
echo 3000 > /proc/sys/net/ipv4/tcp_max_syn_backlog
echo 40960 > /proc/sys/net/ipv4/tcp_max_tw_buckets
echo 4096 87380 16777216 > /proc/sys/net/ipv4/tcp_rmem
echo 0 > /proc/sys/net/ipv4/tcp_slow_start_after_idle
echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse
echo 4096 65536 16777216 > /proc/sys/net/ipv4/tcp_wmem
